# Generated by Django 3.1.5 on 2023-04-05 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('englishclub', '0002_auto_20230405_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabularymodel',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
