# Generated by Django 3.1.5 on 2023-04-10 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('englishclub', '0003_auto_20230405_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestWordsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate', models.CharField(max_length=100, verbose_name='Перевод')),
                ('UserID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
